/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdNotificationsRouteImport } from './routes/projects.$projectId.notifications'
import { Route as ProjectsProjectIdApplicationsApplicationIdRouteImport } from './routes/projects.$projectId.applications.$applicationId'
import { Route as ProjectsProjectIdNotificationsRecoveryRouteImport } from './routes/projects.$projectId.notifications.recovery'
import { Route as AdminProjectsProjectIdApplicationsApplicationIdRouteImport } from './routes/admin.projects.$projectId.applications.$applicationId'
import { Route as ProjectsProjectIdApplicationsApplicationIdAttentionRouteImport } from './routes/projects.$projectId.applications.$applicationId.attention'
import { Route as ProjectsProjectIdApplicationsApplicationIdPoliciesRouteImport } from './routes/projects.$projectId.applications.$applicationId.policies'
import { Route as ProjectsProjectIdApplicationsApplicationIdReleasesRouteImport } from './routes/projects.$projectId.applications.$applicationId.releases'
import { Route as ProjectsProjectIdApplicationsApplicationIdResourcesRouteImport } from './routes/projects.$projectId.applications.$applicationId.resources'
import { Route as ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteImport } from './routes/projects.$projectId.applications.$applicationId.runtime-groups'
import { Route as ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteImport } from './routes/projects.$projectId.applications.$applicationId.runtime-inventory'
import { Route as ProjectsProjectIdNotificationsDeliveriesDeliveryIdRouteImport } from './routes/projects.$projectId.notifications.deliveries.$deliveryId'
import { Route as ProjectsProjectIdNotificationsDestinationsDestinationIdRouteImport } from './routes/projects.$projectId.notifications.destinations.$destinationId'
import { Route as ProjectsProjectIdNotificationsRecoveryOperationIdRouteImport } from './routes/projects.$projectId.notifications.recovery.$operationId'
import { Route as ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRouteImport } from './routes/projects.$projectId.applications.$applicationId.runtime-groups.$groupId'
import { Route as ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRouteImport } from './routes/projects.$projectId.applications.$applicationId.runtime-inventory.$itemId'
import { Route as ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRouteImport } from './routes/projects.$projectId.applications.$applicationId.releases.$targetReleaseId.runtime-diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdNotificationsRoute =
  ProjectsProjectIdNotificationsRouteImport.update({
    id: '/projects/$projectId/notifications',
    path: '/projects/$projectId/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdRoute =
  ProjectsProjectIdApplicationsApplicationIdRouteImport.update({
    id: '/projects/$projectId/applications/$applicationId',
    path: '/projects/$projectId/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdNotificationsRecoveryRoute =
  ProjectsProjectIdNotificationsRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => ProjectsProjectIdNotificationsRoute,
  } as any)
const AdminProjectsProjectIdApplicationsApplicationIdRoute =
  AdminProjectsProjectIdApplicationsApplicationIdRouteImport.update({
    id: '/admin/projects/$projectId/applications/$applicationId',
    path: '/admin/projects/$projectId/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdAttentionRoute =
  ProjectsProjectIdApplicationsApplicationIdAttentionRouteImport.update({
    id: '/attention',
    path: '/attention',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdPoliciesRoute =
  ProjectsProjectIdApplicationsApplicationIdPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdReleasesRoute =
  ProjectsProjectIdApplicationsApplicationIdReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdResourcesRoute =
  ProjectsProjectIdApplicationsApplicationIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute =
  ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteImport.update({
    id: '/runtime-groups',
    path: '/runtime-groups',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute =
  ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteImport.update({
    id: '/runtime-inventory',
    path: '/runtime-inventory',
    getParentRoute: () => ProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute =
  ProjectsProjectIdNotificationsDeliveriesDeliveryIdRouteImport.update({
    id: '/deliveries/$deliveryId',
    path: '/deliveries/$deliveryId',
    getParentRoute: () => ProjectsProjectIdNotificationsRoute,
  } as any)
const ProjectsProjectIdNotificationsDestinationsDestinationIdRoute =
  ProjectsProjectIdNotificationsDestinationsDestinationIdRouteImport.update({
    id: '/destinations/$destinationId',
    path: '/destinations/$destinationId',
    getParentRoute: () => ProjectsProjectIdNotificationsRoute,
  } as any)
const ProjectsProjectIdNotificationsRecoveryOperationIdRoute =
  ProjectsProjectIdNotificationsRecoveryOperationIdRouteImport.update({
    id: '/$operationId',
    path: '/$operationId',
    getParentRoute: () => ProjectsProjectIdNotificationsRecoveryRoute,
  } as any)
const ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute =
  ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRouteImport.update(
    {
      id: '/$groupId',
      path: '/$groupId',
      getParentRoute: () =>
        ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute,
    } as any,
  )
const ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute =
  ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRouteImport.update(
    {
      id: '/$itemId',
      path: '/$itemId',
      getParentRoute: () =>
        ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute,
    } as any,
  )
const ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute =
  ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRouteImport.update(
    {
      id: '/$targetReleaseId/runtime-diff',
      path: '/$targetReleaseId/runtime-diff',
      getParentRoute: () =>
        ProjectsProjectIdApplicationsApplicationIdReleasesRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$applicationId': typeof ProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  '/projects/$projectId/notifications/recovery': typeof ProjectsProjectIdNotificationsRecoveryRouteWithChildren
  '/admin/projects/$projectId/applications/$applicationId': typeof AdminProjectsProjectIdApplicationsApplicationIdRoute
  '/projects/$projectId/applications/$applicationId/attention': typeof ProjectsProjectIdApplicationsApplicationIdAttentionRoute
  '/projects/$projectId/applications/$applicationId/policies': typeof ProjectsProjectIdApplicationsApplicationIdPoliciesRoute
  '/projects/$projectId/applications/$applicationId/releases': typeof ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren
  '/projects/$projectId/applications/$applicationId/resources': typeof ProjectsProjectIdApplicationsApplicationIdResourcesRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren
  '/projects/$projectId/applications/$applicationId/runtime-inventory': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren
  '/projects/$projectId/notifications/deliveries/$deliveryId': typeof ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute
  '/projects/$projectId/notifications/destinations/$destinationId': typeof ProjectsProjectIdNotificationsDestinationsDestinationIdRoute
  '/projects/$projectId/notifications/recovery/$operationId': typeof ProjectsProjectIdNotificationsRecoveryOperationIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute
  '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff': typeof ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs': typeof DocsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$applicationId': typeof ProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  '/projects/$projectId/notifications/recovery': typeof ProjectsProjectIdNotificationsRecoveryRouteWithChildren
  '/admin/projects/$projectId/applications/$applicationId': typeof AdminProjectsProjectIdApplicationsApplicationIdRoute
  '/projects/$projectId/applications/$applicationId/attention': typeof ProjectsProjectIdApplicationsApplicationIdAttentionRoute
  '/projects/$projectId/applications/$applicationId/policies': typeof ProjectsProjectIdApplicationsApplicationIdPoliciesRoute
  '/projects/$projectId/applications/$applicationId/releases': typeof ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren
  '/projects/$projectId/applications/$applicationId/resources': typeof ProjectsProjectIdApplicationsApplicationIdResourcesRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren
  '/projects/$projectId/applications/$applicationId/runtime-inventory': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren
  '/projects/$projectId/notifications/deliveries/$deliveryId': typeof ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute
  '/projects/$projectId/notifications/destinations/$destinationId': typeof ProjectsProjectIdNotificationsDestinationsDestinationIdRoute
  '/projects/$projectId/notifications/recovery/$operationId': typeof ProjectsProjectIdNotificationsRecoveryOperationIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute
  '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff': typeof ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$applicationId': typeof ProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  '/projects/$projectId/notifications/recovery': typeof ProjectsProjectIdNotificationsRecoveryRouteWithChildren
  '/admin/projects/$projectId/applications/$applicationId': typeof AdminProjectsProjectIdApplicationsApplicationIdRoute
  '/projects/$projectId/applications/$applicationId/attention': typeof ProjectsProjectIdApplicationsApplicationIdAttentionRoute
  '/projects/$projectId/applications/$applicationId/policies': typeof ProjectsProjectIdApplicationsApplicationIdPoliciesRoute
  '/projects/$projectId/applications/$applicationId/releases': typeof ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren
  '/projects/$projectId/applications/$applicationId/resources': typeof ProjectsProjectIdApplicationsApplicationIdResourcesRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren
  '/projects/$projectId/applications/$applicationId/runtime-inventory': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren
  '/projects/$projectId/notifications/deliveries/$deliveryId': typeof ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute
  '/projects/$projectId/notifications/destinations/$destinationId': typeof ProjectsProjectIdNotificationsDestinationsDestinationIdRoute
  '/projects/$projectId/notifications/recovery/$operationId': typeof ProjectsProjectIdNotificationsRecoveryOperationIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute
  '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId': typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute
  '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff': typeof ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/verify-email'
    | '/docs/$slug'
    | '/docs/'
    | '/projects/'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/'
    | '/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/notifications/recovery'
    | '/admin/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/applications/$applicationId/attention'
    | '/projects/$projectId/applications/$applicationId/policies'
    | '/projects/$projectId/applications/$applicationId/releases'
    | '/projects/$projectId/applications/$applicationId/resources'
    | '/projects/$projectId/applications/$applicationId/runtime-groups'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory'
    | '/projects/$projectId/notifications/deliveries/$deliveryId'
    | '/projects/$projectId/notifications/destinations/$destinationId'
    | '/projects/$projectId/notifications/recovery/$operationId'
    | '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId'
    | '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/verify-email'
    | '/docs/$slug'
    | '/docs'
    | '/projects'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId'
    | '/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/notifications/recovery'
    | '/admin/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/applications/$applicationId/attention'
    | '/projects/$projectId/applications/$applicationId/policies'
    | '/projects/$projectId/applications/$applicationId/releases'
    | '/projects/$projectId/applications/$applicationId/resources'
    | '/projects/$projectId/applications/$applicationId/runtime-groups'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory'
    | '/projects/$projectId/notifications/deliveries/$deliveryId'
    | '/projects/$projectId/notifications/destinations/$destinationId'
    | '/projects/$projectId/notifications/recovery/$operationId'
    | '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId'
    | '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/verify-email'
    | '/docs/$slug'
    | '/docs/'
    | '/projects/'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/'
    | '/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/notifications/recovery'
    | '/admin/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/applications/$applicationId/attention'
    | '/projects/$projectId/applications/$applicationId/policies'
    | '/projects/$projectId/applications/$applicationId/releases'
    | '/projects/$projectId/applications/$applicationId/resources'
    | '/projects/$projectId/applications/$applicationId/runtime-groups'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory'
    | '/projects/$projectId/notifications/deliveries/$deliveryId'
    | '/projects/$projectId/notifications/destinations/$destinationId'
    | '/projects/$projectId/notifications/recovery/$operationId'
    | '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId'
    | '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId'
    | '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdNotificationsRoute: typeof ProjectsProjectIdNotificationsRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdApplicationsApplicationIdRoute: typeof ProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  AdminProjectsProjectIdApplicationsApplicationIdRoute: typeof AdminProjectsProjectIdApplicationsApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/notifications': {
      id: '/projects/$projectId/notifications'
      path: '/projects/$projectId/notifications'
      fullPath: '/projects/$projectId/notifications'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/applications/$applicationId': {
      id: '/projects/$projectId/applications/$applicationId'
      path: '/projects/$projectId/applications/$applicationId'
      fullPath: '/projects/$projectId/applications/$applicationId'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/notifications/recovery': {
      id: '/projects/$projectId/notifications/recovery'
      path: '/recovery'
      fullPath: '/projects/$projectId/notifications/recovery'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsRecoveryRouteImport
      parentRoute: typeof ProjectsProjectIdNotificationsRoute
    }
    '/admin/projects/$projectId/applications/$applicationId': {
      id: '/admin/projects/$projectId/applications/$applicationId'
      path: '/admin/projects/$projectId/applications/$applicationId'
      fullPath: '/admin/projects/$projectId/applications/$applicationId'
      preLoaderRoute: typeof AdminProjectsProjectIdApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/applications/$applicationId/attention': {
      id: '/projects/$projectId/applications/$applicationId/attention'
      path: '/attention'
      fullPath: '/projects/$projectId/applications/$applicationId/attention'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdAttentionRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/applications/$applicationId/policies': {
      id: '/projects/$projectId/applications/$applicationId/policies'
      path: '/policies'
      fullPath: '/projects/$projectId/applications/$applicationId/policies'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdPoliciesRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/applications/$applicationId/releases': {
      id: '/projects/$projectId/applications/$applicationId/releases'
      path: '/releases'
      fullPath: '/projects/$projectId/applications/$applicationId/releases'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdReleasesRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/applications/$applicationId/resources': {
      id: '/projects/$projectId/applications/$applicationId/resources'
      path: '/resources'
      fullPath: '/projects/$projectId/applications/$applicationId/resources'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdResourcesRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/applications/$applicationId/runtime-groups': {
      id: '/projects/$projectId/applications/$applicationId/runtime-groups'
      path: '/runtime-groups'
      fullPath: '/projects/$projectId/applications/$applicationId/runtime-groups'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/applications/$applicationId/runtime-inventory': {
      id: '/projects/$projectId/applications/$applicationId/runtime-inventory'
      path: '/runtime-inventory'
      fullPath: '/projects/$projectId/applications/$applicationId/runtime-inventory'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/projects/$projectId/notifications/deliveries/$deliveryId': {
      id: '/projects/$projectId/notifications/deliveries/$deliveryId'
      path: '/deliveries/$deliveryId'
      fullPath: '/projects/$projectId/notifications/deliveries/$deliveryId'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsDeliveriesDeliveryIdRouteImport
      parentRoute: typeof ProjectsProjectIdNotificationsRoute
    }
    '/projects/$projectId/notifications/destinations/$destinationId': {
      id: '/projects/$projectId/notifications/destinations/$destinationId'
      path: '/destinations/$destinationId'
      fullPath: '/projects/$projectId/notifications/destinations/$destinationId'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsDestinationsDestinationIdRouteImport
      parentRoute: typeof ProjectsProjectIdNotificationsRoute
    }
    '/projects/$projectId/notifications/recovery/$operationId': {
      id: '/projects/$projectId/notifications/recovery/$operationId'
      path: '/$operationId'
      fullPath: '/projects/$projectId/notifications/recovery/$operationId'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsRecoveryOperationIdRouteImport
      parentRoute: typeof ProjectsProjectIdNotificationsRecoveryRoute
    }
    '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId': {
      id: '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId'
      path: '/$groupId'
      fullPath: '/projects/$projectId/applications/$applicationId/runtime-groups/$groupId'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute
    }
    '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId': {
      id: '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId'
      path: '/$itemId'
      fullPath: '/projects/$projectId/applications/$applicationId/runtime-inventory/$itemId'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute
    }
    '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff': {
      id: '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff'
      path: '/$targetReleaseId/runtime-diff'
      fullPath: '/projects/$projectId/applications/$applicationId/releases/$targetReleaseId/runtime-diff'
      preLoaderRoute: typeof ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRouteImport
      parentRoute: typeof ProjectsProjectIdApplicationsApplicationIdReleasesRoute
    }
  }
}

interface ProjectsProjectIdNotificationsRecoveryRouteChildren {
  ProjectsProjectIdNotificationsRecoveryOperationIdRoute: typeof ProjectsProjectIdNotificationsRecoveryOperationIdRoute
}

const ProjectsProjectIdNotificationsRecoveryRouteChildren: ProjectsProjectIdNotificationsRecoveryRouteChildren =
  {
    ProjectsProjectIdNotificationsRecoveryOperationIdRoute:
      ProjectsProjectIdNotificationsRecoveryOperationIdRoute,
  }

const ProjectsProjectIdNotificationsRecoveryRouteWithChildren =
  ProjectsProjectIdNotificationsRecoveryRoute._addFileChildren(
    ProjectsProjectIdNotificationsRecoveryRouteChildren,
  )

interface ProjectsProjectIdNotificationsRouteChildren {
  ProjectsProjectIdNotificationsRecoveryRoute: typeof ProjectsProjectIdNotificationsRecoveryRouteWithChildren
  ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute: typeof ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute
  ProjectsProjectIdNotificationsDestinationsDestinationIdRoute: typeof ProjectsProjectIdNotificationsDestinationsDestinationIdRoute
}

const ProjectsProjectIdNotificationsRouteChildren: ProjectsProjectIdNotificationsRouteChildren =
  {
    ProjectsProjectIdNotificationsRecoveryRoute:
      ProjectsProjectIdNotificationsRecoveryRouteWithChildren,
    ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute:
      ProjectsProjectIdNotificationsDeliveriesDeliveryIdRoute,
    ProjectsProjectIdNotificationsDestinationsDestinationIdRoute:
      ProjectsProjectIdNotificationsDestinationsDestinationIdRoute,
  }

const ProjectsProjectIdNotificationsRouteWithChildren =
  ProjectsProjectIdNotificationsRoute._addFileChildren(
    ProjectsProjectIdNotificationsRouteChildren,
  )

interface ProjectsProjectIdApplicationsApplicationIdReleasesRouteChildren {
  ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute: typeof ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute
}

const ProjectsProjectIdApplicationsApplicationIdReleasesRouteChildren: ProjectsProjectIdApplicationsApplicationIdReleasesRouteChildren =
  {
    ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute:
      ProjectsProjectIdApplicationsApplicationIdReleasesTargetReleaseIdRuntimeDiffRoute,
  }

const ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren =
  ProjectsProjectIdApplicationsApplicationIdReleasesRoute._addFileChildren(
    ProjectsProjectIdApplicationsApplicationIdReleasesRouteChildren,
  )

interface ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteChildren {
  ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute
}

const ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteChildren: ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteChildren =
  {
    ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute:
      ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsGroupIdRoute,
  }

const ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren =
  ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute._addFileChildren(
    ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteChildren,
  )

interface ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteChildren {
  ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute
}

const ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteChildren: ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteChildren =
  {
    ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute:
      ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryItemIdRoute,
  }

const ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren =
  ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute._addFileChildren(
    ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteChildren,
  )

interface ProjectsProjectIdApplicationsApplicationIdRouteChildren {
  ProjectsProjectIdApplicationsApplicationIdAttentionRoute: typeof ProjectsProjectIdApplicationsApplicationIdAttentionRoute
  ProjectsProjectIdApplicationsApplicationIdPoliciesRoute: typeof ProjectsProjectIdApplicationsApplicationIdPoliciesRoute
  ProjectsProjectIdApplicationsApplicationIdReleasesRoute: typeof ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren
  ProjectsProjectIdApplicationsApplicationIdResourcesRoute: typeof ProjectsProjectIdApplicationsApplicationIdResourcesRoute
  ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren
  ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute: typeof ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren
}

const ProjectsProjectIdApplicationsApplicationIdRouteChildren: ProjectsProjectIdApplicationsApplicationIdRouteChildren =
  {
    ProjectsProjectIdApplicationsApplicationIdAttentionRoute:
      ProjectsProjectIdApplicationsApplicationIdAttentionRoute,
    ProjectsProjectIdApplicationsApplicationIdPoliciesRoute:
      ProjectsProjectIdApplicationsApplicationIdPoliciesRoute,
    ProjectsProjectIdApplicationsApplicationIdReleasesRoute:
      ProjectsProjectIdApplicationsApplicationIdReleasesRouteWithChildren,
    ProjectsProjectIdApplicationsApplicationIdResourcesRoute:
      ProjectsProjectIdApplicationsApplicationIdResourcesRoute,
    ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRoute:
      ProjectsProjectIdApplicationsApplicationIdRuntimeGroupsRouteWithChildren,
    ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRoute:
      ProjectsProjectIdApplicationsApplicationIdRuntimeInventoryRouteWithChildren,
  }

const ProjectsProjectIdApplicationsApplicationIdRouteWithChildren =
  ProjectsProjectIdApplicationsApplicationIdRoute._addFileChildren(
    ProjectsProjectIdApplicationsApplicationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdNotificationsRoute:
    ProjectsProjectIdNotificationsRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdApplicationsApplicationIdRoute:
    ProjectsProjectIdApplicationsApplicationIdRouteWithChildren,
  AdminProjectsProjectIdApplicationsApplicationIdRoute:
    AdminProjectsProjectIdApplicationsApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
